### ISSUE TITLE
Ошибка установки

### ISSUE THREAD

**Issue by just-website** [Zevsus/confidicila#2]
Xiaomi mi 6
MIUI Global 11.0.6 Stable
Android 9 PKQ1.190118.001
Никаких рутов или других вмешательств в систему.
При попытке обновить приложение появляется надпись "Приложение не установлено"

**Comment by Zevsus** [comment]
Здраствуйте! Возможно предидущая версия приложения установлена из другого источника (плеймаркет, то установить обновление, сайты типа 4pda, то удалить из установить свежую версию). ПРичина скорее только в этом.

**Comment by Zevsus** [comment]
Ответ выше

**Comment by just-website** [comment]
Да, была версия с 4pda, как оказалось с вырезанной рекламой.
Как то можно рекламу отключить в вашем приложении? Готов задонатить, но не через play market (приложение "недоступно в вашей стране").

**Comment by Zevsus** [comment]
Есть же другие варианты (AdGuard)
